# Generated by Django 2.1.7 on 2021-01-12 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_auto_20201210_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(default='', max_length=10, verbose_name='状态'),
            preserve_default=False,
        ),
    ]
