# Generated by Django 2.1.7 on 2021-01-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0004_article_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='permission',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
