# Generated by Django 2.1.7 on 2021-01-25 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0005_article_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='status',
        ),
    ]
