# Generated by Django 2.1.7 on 2021-01-26 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0007_auto_20210125_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='canEdit',
            field=models.IntegerField(default=1),
        ),
    ]
