# Generated by Django 2.1.7 on 2021-01-29 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0009_article_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='reason',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='理由'),
        ),
    ]
